import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/common/rgemployee/Navbar";
import Sidebar from "@/components/common/rgemployee/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RG Employee Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

        <div className="flex flex-col h-screen">
          <Navbar className='flex-grow-0'></Navbar>
          <div className="flex flex-grow md:flex-row flex-col overflow-hidden">
            <Sidebar></Sidebar>
            {children}
          </div>
        </div>
  );
}
